const firstName='Mandy';
const lastName='Gill';
const age=25;
const dob='Aug-25-1992';
const address='944G, Chancelor Drive';
firstName='abc';
console.log('First_name:',firstName);
console.log('Age:',age);
console.log('Dob:',dob);
console.log('Address:',address);